### ISSUE TITLE
Version always shows “Brain 0.1.0”

### ISSUE THREAD

**Issue by kseistrup** [robert-lag/brain#1]
Yesterday I updated `brn` to [v2.2](https://github.com/robert-lag/brain/releases/tag/v2.2). However, `brn` still reports v0.1.0:

```sh
$ brn --version
Brain 0.1.0
```

**Comment by kseistrup** [comment]
**P**.**S**: The “always“ refer to the similar behaviour of v2.1, but at that time I didn't have time/energy to report it (or I wasn't sufficiently unamused).

**Comment by robert-lag** [comment]
Thanks for the feedback. I will look into it ;)

**Comment by robert-lag** [comment]
Fixed in version 2.3. Note that all previous versions will still display `v0.1.0`.
